### ISSUE TITLE
Added eot parameter to JSON?

### ISSUE THREAD

**Issue by hongkongkiwi** [mob41/KmbETA-API#2]
Looks like there is a new parameter added to the JSON called returned called "eot".

Any idea what this could be?

**Comment by a1aw** [comment]
@hongkongkiwi Sorry for late reply, I was so busy these days on exam... I will reply you after few minutes...

**Comment by a1aw** [comment]
@hongkongkiwi That isn't new. That parameter is already exist for a while. What I can fetch, there is two possible value `E` and `T`. I think they are "Estimated Time Arrival" for "E" and "Schedule Time" for "T"

**Comment by mob41** [comment]
May be I will implement it to the API afterwards.

**Comment by a1aw** [comment]
If no problem, I will close it now.
