### ISSUE TITLE
Database download error (https://db.kmbeta.ml/kmbeta_db.json)

### ISSUE THREAD

**Issue by leonso** [mob41/KmbETA-API#3]
https://db.kmbeta.ml/kmbeta_db.json no long exist

**Comment by a1aw** [comment]
Well, I'm pretty sorry for that. The domain was just put down by the provider, as seems I got something wrong with their terms. (I have no dns records on the root domain)

I will fix this among this week. I would like to apologise for this.

**Comment by a1aw** [comment]
You can download the offline version from here.

https://github.com/mob41/KmbETA-DB/blob/gh-pages/kmbeta_db.json

**Comment by a1aw** [comment]
@leonso The domain is back right now. https://db.kmbeta.ml/
