### ISSUE TITLE
Unreasonable API Take-down from old KMB-App

### ISSUE THREAD

**Issue by a1aw** [mob41/KmbETA-API#9]
This really surprised me. The API suddenly changes. The old API no longer works.

**Comment by aldenleung** [comment]
You can simply update the ETA server address to "http://etav3.kmb.hk/" and the API will work again.

**Comment by a1aw** [comment]
I am quite busy these days and I wasn't able to do packet sniffing. Thanks for noticing me the changes of the API server.

But this API still need to be rewritten as some new features of the Official API haven't added to this

**Comment by hungyip** [comment]
Is this project still alive? I want to fetch ETA data for my home automation project but have no idea how to do it. Any advice is appreciated, thanks.

**Comment by a1aw** [comment]
This project is currently inactive. However, it should still work with the current API, but without new parameters from the official API.

The WIP JavaScript API is active and it follows with the current new API parameters. You may take a look of it here: https://github.com/mob41/KmbETA-API/blob/gh-pages/js/KmbETA.js

Change ETA and datafeed server to KMB official ones to use it.
